spring.application.name=services-client
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR}
#spring.cloud.nacos.discovery.group=my_discovery
#spring.config.import=nacos:server-order.properties?refreshEnabled=true&group=my_discovery
spring.config.import=nacos:server-order.properties?refreshEnabled=true

server.port=8083
