spring:
  ai:
#    mcp:
#      client:
#        sse:
#          connections:
#            zhipuaiMcpClient:
#              url: https://open.bigmodel.cn/api/mcp/web_search/sse?Authorization=${spring.ai.zhipuai.api-key}
    chat:

      memory:
        repository:
          jdbc:
            schema:  classpath:db/chat-memory.sql
    model:
      chat: zhipuai
    zhipuai:
      api-key:  ${ZHIPUAI_API_KEY}
      chat:
        options:
          model: glm-4-plus
      embedding:
        options:
          model: embedding-3
    vectorstore:
      type: false
#       由于底层貌似不支持多数据源，为了避免和聊天缓存用的mysql冲突，自行配置org.example.config.MyVectorStore
#      pgvector:
#        dimensions:  2048
#        index-type: hnsw
#        distance-type: cosine_distance
#        initialize-schema: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.36.124:3306/spring-ai?serverTimezone=Asia/Shanghai&userUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 465700

logging:
  level:
    org.springframework.ai:  DEBUG







