spring:
  datasource:
    url: jdbc:mysql://localhost:3307/root1?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 465700
    driver-class-name: com.mysql.cj.jdbc.Driver