spring:
  application:
    name:  gateway
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR}
      discovery:
        group: my_discovery
        server-addr: ${NACOS_SERVER_ADDR}
    gateway:
#      动态加载网关，从编码角度上实现
      routes:
#        - id: method_route
#          uri: lb://services-order
#          predicates:
#            - Method=GET
        - id: path_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/test/test/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
server:
  port: 80
