name: fklasj

myPort: 88
server:
  port: ${myPort:88}


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/root1?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 465700
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.sangeng.domain   # 配置哪个包下的类有默认的别名


stu:
  name: sangeng2
  age: 15
