dubbo:
  application:
    name: dubbo-register-zk-consumer
    qos-enable:  false
    register-mode:  interface
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
